name: Release build 😎

on:
  push:
    branches:
    - 'release/**'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #UNITY_VERSION: 2022.2.12f1  

jobs:
  build-Standalone:
    name: Build for ${{ matrix.targetPlatform }} ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion: 
          - 2022.2.12f1
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          # - StandaloneLinux64
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          #UNITY_VERSION: 2022.2.12f1
        with:
          unityVersion: ${{ matrix.unityVersion }}
          #customImage: 'unityci/editor:2022.2.12f1-base-1.0.1'
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: KitchenChaos-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  # build-WebGL:
  #   name: Build for WebGL ✨
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       targetPlatform:
  #         - WebGL

  #   steps:
  #     # Checkout
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         lfs: true

  #     # Cache
  #     - uses: actions/cache@v3
  #       with:
  #         path: Library
  #         key: Library-${{ matrix.targetPlatform }}
  #         restore-keys: |
  #           Library-

  #     # Build
  #     - name: Build project
  #       uses: game-ci/unity-builder@v2
  #       env:
  #         UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #         UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #       with:
  #         targetPlatform: ${{ matrix.targetPlatform }}

  #     # Output
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: KitchenChaos-${{ matrix.targetPlatform }}
  #         path: build/${{ matrix.targetPlatform }}

  # deployToPages:
  #   needs: build-WebGL
  #   name: Deploy to Github Pages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: KitchenChaos-WebGL
  #         path: build/WebGL

  #     - name: Display structure of root files
  #       run: ls -R
  #       #working-directory: build/WebGL

  #     - name: Deploy
  #       uses: JamesIves/github-pages-deploy-action@v4
  #       with:
  #         branch: gh-pages
  #         folder: build/WebGL/WebGL
  #         target-folder: .